services:
  - type: web
    name: speed-sudoku-support-site
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
